services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - ${PORT}:5000
      - 24678:24678
    command: npm run start
    tty: true

volumes:
  node_modules:
